import { DaySchedule, StudentInfo, SubjectGrades } from '@/types/librus';

export const mockStudentInfo: StudentInfo = {
  name: 'Jan Kowalski',
  classGroup: '2B - profil mat-inf',
  indexNumber: '482910',
  educator: 'mgr Anna Nowak',
  luckyNumber: 14,
  studentNumber: 14, // Dziś masz szczęśliwy numerek!
};

export const mockSubjects: SubjectGrades[] = [
  {
    id: 'mat',
    subjectName: 'Matematyka',
    averageSem1: 4.65,
    averageSem2: 4.80,
    yearAverage: 4.72,
    predictedGrade: '5',
    grades: [
      {
        id: 'm1',
        value: '5',
        numericValue: 5,
        weight: 3,
        category: 'Sprawdzian',
        date: '2026-03-02',
        teacher: 'A. Nowak',
        comment: 'Funkcja kwadratowa',
        semester: 2,
      },
      {
        id: 'm2',
        value: '5+',
        numericValue: 5.5,
        weight: 2,
        category: 'Kartkówka',
        date: '2026-02-24',
        teacher: 'A. Nowak',
        comment: 'Wierzchołek paraboli',
        semester: 2,
      },
      {
        id: 'm3',
        value: '4',
        numericValue: 4,
        weight: 1,
        category: 'Aktywność',
        date: '2026-02-18',
        teacher: 'A. Nowak',
        comment: 'Zadania domowe',
        semester: 2,
      },
      {
        id: 'm4',
        value: '5',
        numericValue: 5,
        weight: 3,
        category: 'Sprawdzian',
        date: '2025-11-14',
        teacher: 'A. Nowak',
        comment: 'Wielomiany',
        semester: 1,
      },
      {
        id: 'm5',
        value: '4+',
        numericValue: 4.5,
        weight: 2,
        category: 'Kartkówka',
        date: '2025-10-20',
        teacher: 'A. Nowak',
        semester: 1,
      },
    ],
  },
  {
    id: 'inf',
    subjectName: 'Informatyka',
    averageSem1: 5.4,
    averageSem2: 5.6,
    yearAverage: 5.5,
    predictedGrade: '6',
    grades: [
      {
        id: 'i1',
        value: '6',
        numericValue: 6,
        weight: 3,
        category: 'Projekt',
        date: '2026-03-05',
        teacher: 'T. Wiśniewski',
        comment: 'Aplikacja mobilna React Native',
        semester: 2,
      },
      {
        id: 'i2',
        value: '5',
        numericValue: 5,
        weight: 2,
        category: 'Ćwiczenia',
        date: '2026-02-20',
        teacher: 'T. Wiśniewski',
        comment: 'Algorytmy sortowania',
        semester: 2,
      },
      {
        id: 'i3',
        value: '6',
        numericValue: 6,
        weight: 3,
        category: 'Sprawdzian',
        date: '2025-12-08',
        teacher: 'T. Wiśniewski',
        semester: 1,
      },
    ],
  },
  {
    id: 'ang',
    subjectName: 'Język angielski',
    averageSem1: 4.8,
    averageSem2: 4.5,
    yearAverage: 4.65,
    predictedGrade: '5',
    grades: [
      {
        id: 'a1',
        value: '4+',
        numericValue: 4.5,
        weight: 2,
        category: 'Kartkówka',
        date: '2026-03-04',
        teacher: 'M. Zielińska',
        comment: 'Conditionals (0, 1, 2)',
        semester: 2,
      },
      {
        id: 'a2',
        value: '5',
        numericValue: 5,
        weight: 3,
        category: 'Writing',
        date: '2026-02-15',
        teacher: 'M. Zielińska',
        comment: 'Essay on modern tech',
        semester: 2,
      },
      {
        id: 'a3',
        value: '5',
        numericValue: 5,
        weight: 2,
        category: 'Odpowiedź',
        date: '2025-11-20',
        teacher: 'M. Zielińska',
        semester: 1,
      },
    ],
  },
  {
    id: 'pol',
    subjectName: 'Język polski',
    averageSem1: 4.1,
    averageSem2: 4.25,
    yearAverage: 4.18,
    predictedGrade: '4',
    grades: [
      {
        id: 'p1',
        value: '4',
        numericValue: 4,
        weight: 3,
        category: 'Wypracowanie',
        date: '2026-02-28',
        teacher: 'K. Dąbrowska',
        comment: 'Motyw miłości w "Lalce"',
        semester: 2,
      },
      {
        id: 'p2',
        value: '5',
        numericValue: 5,
        weight: 1,
        category: 'Aktywność',
        date: '2026-02-14',
        teacher: 'K. Dąbrowska',
        semester: 2,
      },
      {
        id: 'p3',
        value: '4',
        numericValue: 4,
        weight: 3,
        category: 'Sprawdzian',
        date: '2025-12-12',
        teacher: 'K. Dąbrowska',
        semester: 1,
      },
    ],
  },
  {
    id: 'fiz',
    subjectName: 'Fizyka',
    averageSem1: 4.5,
    averageSem2: 4.33,
    yearAverage: 4.42,
    predictedGrade: '4',
    grades: [
      {
        id: 'f1',
        value: '5',
        numericValue: 5,
        weight: 2,
        category: 'Laboratorium',
        date: '2026-03-01',
        teacher: 'P. Lewandowski',
        comment: 'Wyznaczanie współczynnika sprężystości',
        semester: 2,
      },
      {
        id: 'f2',
        value: '4-',
        numericValue: 3.75,
        weight: 3,
        category: 'Sprawdzian',
        date: '2026-02-10',
        teacher: 'P. Lewandowski',
        comment: 'Elektrodynamika',
        semester: 2,
      },
    ],
  },
  {
    id: 'chem',
    subjectName: 'Chemia',
    averageSem1: 4.0,
    averageSem2: 4.5,
    yearAverage: 4.25,
    predictedGrade: '4',
    grades: [
      {
        id: 'c1',
        value: '5',
        numericValue: 5,
        weight: 2,
        category: 'Kartkówka',
        date: '2026-02-25',
        teacher: 'E. Kamińska',
        comment: 'Węglowodory nasycone',
        semester: 2,
      },
      {
        id: 'c2',
        value: '4',
        numericValue: 4,
        weight: 3,
        category: 'Sprawdzian',
        date: '2025-11-28',
        teacher: 'E. Kamińska',
        semester: 1,
      },
    ],
  },
  {
    id: 'wf',
    subjectName: 'Wychowanie fizyczne',
    averageSem1: 5.5,
    averageSem2: 6.0,
    yearAverage: 5.75,
    predictedGrade: '6',
    grades: [
      {
        id: 'w1',
        value: '6',
        numericValue: 6,
        weight: 2,
        category: 'Zaangażowanie',
        date: '2026-03-06',
        teacher: 'M. Wójcik',
        semester: 2,
      },
      {
        id: 'w2',
        value: '6',
        numericValue: 6,
        weight: 2,
        category: 'Siatkówka',
        date: '2026-02-17',
        teacher: 'M. Wójcik',
        semester: 2,
      },
    ],
  },
];

export const mockTimetable: DaySchedule[] = [
  {
    dayId: 1,
    dayName: 'Poniedziałek',
    shortName: 'Pon',
    date: '10 marca',
    lessons: [
      {
        id: 'mon-1',
        hourNumber: 1,
        timeSpan: '08:00 - 08:45',
        subject: 'Matematyka',
        teacher: 'mgr A. Nowak',
        classroom: 's. 24',
      },
      {
        id: 'mon-2',
        hourNumber: 2,
        timeSpan: '08:50 - 09:35',
        subject: 'Matematyka',
        teacher: 'mgr A. Nowak',
        classroom: 's. 24',
      },
      {
        id: 'mon-3',
        hourNumber: 3,
        timeSpan: '09:45 - 10:30',
        subject: 'Język angielski',
        teacher: 'mgr M. Zielińska',
        classroom: 's. 12',
      },
      {
        id: 'mon-4',
        hourNumber: 4,
        timeSpan: '10:45 - 11:30',
        subject: 'Informatyka',
        teacher: 'mgr inż. T. Wiśniewski',
        classroom: 'prac. 104',
      },
      {
        id: 'mon-5',
        hourNumber: 5,
        timeSpan: '11:45 - 12:30',
        subject: 'Fizyka',
        teacher: 'dr P. Lewandowski',
        classroom: 's. 31',
      },
    ],
  },
  {
    dayId: 2,
    dayName: 'Wtorek',
    shortName: 'Wt',
    date: '11 marca',
    lessons: [
      {
        id: 'tue-1',
        hourNumber: 1,
        timeSpan: '08:00 - 08:45',
        subject: 'Język polski',
        teacher: 'mgr K. Dąbrowska',
        classroom: 's. 15',
      },
      {
        id: 'tue-2',
        hourNumber: 2,
        timeSpan: '08:50 - 09:35',
        subject: 'Język polski',
        teacher: 'mgr K. Dąbrowska',
        classroom: 's. 15',
      },
      {
        id: 'tue-3',
        hourNumber: 3,
        timeSpan: '09:45 - 10:30',
        subject: 'Chemia',
        teacher: 'mgr E. Kamińska',
        classroom: 's. 08',
      },
      {
        id: 'tue-4',
        hourNumber: 4,
        timeSpan: '10:45 - 11:30',
        subject: 'Historia',
        teacher: 'mgr J. Szymański',
        classroom: 's. 19',
      },
      {
        id: 'tue-5',
        hourNumber: 5,
        timeSpan: '11:45 - 12:30',
        subject: 'Wychowanie fizyczne',
        teacher: 'mgr M. Wójcik',
        classroom: 'SG 2',
      },
      {
        id: 'tue-6',
        hourNumber: 6,
        timeSpan: '12:45 - 13:30',
        subject: 'Wychowanie fizyczne',
        teacher: 'mgr M. Wójcik',
        classroom: 'SG 2',
      },
    ],
  },
  {
    dayId: 3,
    dayName: 'Środa',
    shortName: 'Śr',
    date: '12 marca',
    lessons: [
      {
        id: 'wed-1',
        hourNumber: 2,
        timeSpan: '08:50 - 09:35',
        subject: 'Informatyka',
        teacher: 'mgr inż. T. Wiśniewski',
        classroom: 'prac. 104',
      },
      {
        id: 'wed-2',
        hourNumber: 3,
        timeSpan: '09:45 - 10:30',
        subject: 'Matematyka',
        teacher: 'mgr A. Nowak',
        classroom: 's. 24',
      },
      {
        id: 'wed-3',
        hourNumber: 4,
        timeSpan: '10:45 - 11:30',
        subject: 'Biologia',
        teacher: 'mgr A. Kozłowska',
        classroom: 's. 22',
      },
      {
        id: 'wed-4',
        hourNumber: 5,
        timeSpan: '11:45 - 12:30',
        subject: 'Język angielski',
        teacher: 'mgr M. Zielińska',
        classroom: 's. 12',
      },
    ],
  },
  {
    dayId: 4,
    dayName: 'Czwartek',
    shortName: 'Czw',
    date: '13 marca',
    lessons: [
      {
        id: 'thu-1',
        hourNumber: 1,
        timeSpan: '08:00 - 08:45',
        subject: 'Geografia',
        teacher: 'mgr R. Mazur',
        classroom: 's. 18',
      },
      {
        id: 'thu-2',
        hourNumber: 2,
        timeSpan: '08:50 - 09:35',
        subject: 'Fizyka',
        teacher: 'dr P. Lewandowski',
        classroom: 's. 31',
      },
      {
        id: 'thu-3',
        hourNumber: 3,
        timeSpan: '09:45 - 10:30',
        subject: 'Język polski',
        teacher: 'mgr K. Dąbrowska',
        classroom: 's. 15',
      },
      {
        id: 'thu-4',
        hourNumber: 4,
        timeSpan: '10:45 - 11:30',
        subject: 'Matematyka',
        teacher: 'mgr A. Nowak',
        classroom: 's. 24',
      },
    ],
  },
  {
    dayId: 5,
    dayName: 'Piątek',
    shortName: 'Pt',
    date: '14 marca',
    lessons: [
      {
        id: 'fri-1',
        hourNumber: 2,
        timeSpan: '08:50 - 09:35',
        subject: 'Język niemiecki',
        teacher: 'mgr B. Kaczmarek',
        classroom: 's. 11',
      },
      {
        id: 'fri-2',
        hourNumber: 3,
        timeSpan: '09:45 - 10:30',
        subject: 'Język angielski',
        teacher: 'mgr M. Zielińska',
        classroom: 's. 12',
      },
      {
        id: 'fri-3',
        hourNumber: 4,
        timeSpan: '10:45 - 11:30',
        subject: 'Godzina z wychowawcą',
        teacher: 'mgr A. Nowak',
        classroom: 's. 24',
      },
    ],
  },
];
